[tool.poetry]
name = "zhhanzi"
version = "0.1.0"
description = ""
authors = ["patarapolw <patarapolw@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
zhlib = {path = "../zhlib"}

[tool.poetry.dev-dependencies]
